

spring:
    datasource:
        url: jdbc:mysql://nokkaedb.cdfonnhdltpr.ap-northeast-2.rds.amazonaws.com:3306/carrot
        username: nokkae
        password: dmlwls12
    jpa:
        hibernate:
            ddl-auto: create
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
